name: Deploy on dev Push

on:
    push:
        branches:
            - dev

jobs:
    prettier-check:
        name: Prettier Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: yarn install --force

            - name: Run Prettier check
              run: yarn prettier:check

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: prettier-check
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: yarn install --force

            - name: SSH into the server and deploy
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.REMOTE_IP }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.REMOTE_PRIVATE_KEY }}
                  port: ${{ secrets.REMOTE_SSH_PORT }}
                  script: |
                      cd /home/ubuntu/BACK-CT1
                      git pull origin dev
                      pm2 kill || true
                      yarn install --force
                      pm2 start src/app.js
