# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
    push:
        branches: dev
    pull_request:
        branches: dev

jobs:
    build:
        runs-on: ubuntu-22.04

        strategy:
            matrix:
                node-version: v18.x.x

        steps:
            - name: Checkout source code.
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Check Npm -v
              run: npm -v

            - name: create env file
              working-directory: ./
              run: |
                  pwd
                  touch .env
                  echo DB_URL=${{ secrets.DB_URL }} >> .env
                  echo ACESS_TOKEN=${{ secrets.ACESS_TOKEN }} >> .env
                  echo REFRESG_TOKEN=${{ secrets.REFRESG_TOKEN }} >> .env
                  echo AWS_ACCESS=${{ secrets.AWS_ACCESS }} >> .env
                  echo AWS_SECRET_ACCESS=${{ secrets.AWS_SECRET_ACCESS }} >> .env
                  echo BUCKET=${{ secrets.BUCKET }} >> .env

                  cat .env

            - name: build server files
              working-directory: ./
              run: |
                  yarn
                  yarn run build
