name: Deploy on dev Push

on:
    push:
        branches:
            - dev

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install dependencies
              run: yarn install --force

            - name: SSH into the server and deploy
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.REMOTE_IP }}
                  username: ${{ secrets.REMOTE_USER }}
                  key: ${{ secrets.REMOTE_PRIVATE_KEY }}
                  port: ${{ secrets.REMOTE_SSH_PORT }}
                  script: |
                      cd ~/BACK-CT1
                      git pull origin dev
                      pm2 restart app.js
              env:
                  DATABASE_URL: ${{ secrets.DB_URL}}
                  ACCESS_TOKEN_SECRET: ${{ secrets.ACESS_TOKEN }}
                  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESG_TOKEN }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS }}
                  AWS_BUCKET_NAME: ${{ secrets.BUCKET }}
